### ISSUE TITLE
Ingress controller does not allow uploading files bigger than 5MB

### ISSUE THREAD

**Issue by miwurster** [radon-h2020/radon-ide#35] opened 2020-09-22 12:37 UTC
Currently it seems that the configured Ingress controller of RADON's Kubernetes cluster does not allow to upload files bigger than X megabytes (tested it with a file of 8MB). 

The Ingress layer returns a "413 Request Entity Too Large" error depicted in the following screenshot:
![image](https://user-images.githubusercontent.com/2610997/93882722-ea2e5400-fce0-11ea-8c7f-8b4aeb3bfe7d.png)

We may have to configure the underlying nginx configuration to solve this. See here: https://github.com/kubernetes/ingress-nginx/issues/4825#issuecomment-564662583

**Comment by miwurster** [comment] 2021-02-16 09:25
@sdagostini any update on this? 
IMHO we should work on this till the final release.

**Comment by sdagostini** [comment] 2021-02-16 09:51
@miwurster Hi, I don't have updates yet but yes, the idea is to solve it for the final release. I will update you on that issue as soon as possible.

**Comment by sdagostini** [comment] 2021-03-04 12:46
@miwurster Hi, just to let you know that I have updated the underlying nginx configuration of the "che" ingress to allow uploading files up to 16MB but the issue is not been solved. This is the motivation: when a new RADON workspace is created a new ingress is created for the GMT component (e.g. servernjp9g1pa-winery-deployment-winery-server-8080.217.172.12.178.nip.io). In order to fix the issue the configuration of the created ingress should be updated (i.e. for each new GMT instance created for each workspace). Therefore, if there is no way to increse the file size when the GMT kubernetes container is created I think that we have to limit the size to 5MB

**Comment by miwurster** [comment] 2021-03-04 12:58
Have you tried to find some information if some default value can be set for the ingress. To my knowledge, the ingress is created behind the scene by che. So you cannot influence it from the devfile. Nevertheless, if you find some information on how to this from the devfile, please forward it.

**Comment by sdagostini** [comment] 2021-03-05 14:44
@miwurster Hi, I have updated the  configMap for the nginx ingress controller to allow uploading files up to 16MB. Now it works. Please, let me know if we need to increse more the size otherwise I will close the issue

**Comment by miwurster** [comment] 2021-03-05 14:46
Nice! I would suggest going for 100MB ;-) Then we can close this!

**Comment by sdagostini** [comment] 2021-03-08 10:53
The size has been increased to 100MB.

**Closed by sdagostini** 2021-03-08 10:53 UTC
